### ISSUE TITLE
on_raw_reaction_add erroring out

### ISSUE THREAD

**Issue by dartmern** [dartmern/metro#4]
There seems to be an issue with requirement giveaways in the `on_raw_reaction_add` event.

Traceback below:
```py
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/discord/client.py", line 376, in _run_event
    await coro(*args, **kwargs)
  File "/home/pi/Documents/metro-master/cogs/giveaway.py", line 95, in on_raw_reaction_add
    requirements = json.loads(data['extra'])['kwargs']['requirements']
TypeError: 'NoneType' object is not subscriptable
```

doesn't seem to break anything at the moment.

**Comment by dartmern** [comment]
Should be fixed.
