### ISSUE TITLE
[music] Stop command not working

### ISSUE THREAD

**Issue by dartmern** [dartmern/metro#8]
**Description**
The stop command doesn't work.

**To Reproduce**
1. Play a song with `/play ...`
2. Use `/stop` to stop the player.
3. See the error.

**Expected behavior**
The bot stops the player and leave the voice channel.

**Traceback**
```py
Traceback (most recent call last):
  File "/home/pi/Documents/metro/lib/python3.10/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/pi/Documents/metro/cogs/music.py", line 441, in stop
    if len(player.stop_votes) >= required:
TypeError: '>=' not supported between instances of 'int' and 'coroutine'
```

**Comment by dartmern** [comment]
Seems to only error when a vote needs to be casted. (more than 1 person using music)
